### ISSUE TITLE
Document how to use Gromacs

### ISSUE THREAD

**Issue by MarionBWeinzierl** [N8-CIR-Bede/documentation#79] opened 2021-11-24 11:36 UTC
Talk to James Gebbie about how to use Gromacs and add the information to the docs

**Comment by ptheywood** [comment] 2021-11-24 12:42
I've added some basic Gromacs documentation in PR #67. 

This is also a duplicate of #37.

**Comment by ptheywood** [comment] 2022-02-08 12:21
Now #67 is merged, the very basic Gromacs documentation can be exapended by editing [software/applications/gromacs.rst](https://github.com/N8-CIR-Bede/documentation/blob/main/software/applications/gromacs.rst)

**Comment by ptheywood** [comment] 2022-06-07 09:42
Closing this as the docs taskforce is being closed. The docs page can still be expanded if required with bede-speicifc additions if required.

**Closed by ptheywood** 2022-06-07 09:42 UTC
